# Generated by Django 3.2.15 on 2023-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugs',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
